using System;

namespace ONE.Models.MessageContracts
{
    public interface IONEEventMessage
    {
        Guid GlobalTrackingGuid { get; set; }

        //This is generated by the event interpreter at the time of event firing
        Guid EventInstanceGUID { get; set; }

        //Need to change it to enumtype
        Models.Enumerations.EventType EventType { get; set; }

        Guid InitiatorGUID { get; set; }

        Guid EventFlowGUID { get; set; }

        object Payload { get; set; }

        Guid? TriggeredByEventFlowInstanceGUID { get; set; }

        string EventFlowLogDetailXML { get; set; }


        /// <summary>
        /// Gets or sets the halted by event flow instance unique identifier.
        /// </summary>
        /// <value>
        /// The halted by event flow instance unique identifier.
        /// </value>
        Guid? HaltedByEventFlowInstanceGUID { get; set; }

        bool StopAudioOnEventFlowHalt { get; set; }
    }

}
