namespace ONE.Models.Enumerations
{
    public enum EventType
    {
        FirstActivation = 1,
        FirstActivationClear = 2,
        SecondActivation = 3,
        SecondActivationClear = 4,
        ThirdActivation = 5,
        ThirdActivationClear = 6,
        FourthActivation = 7,
        FourthActivationClear = 8,
        Tamper = 33,
        Checkin = 36,
        CheckinFailure = 37,
        CleanMe = 46,
        EolTamper = 49,
        InternalLowBattery = 50,
        PrimaryLowBattery = 51,
        PrimaryBatteryMissing = 52,
        Reset = 53,
        Test = 58,
        LowSignalStrength = 59,
        CheckinFailureClear = 60,
        CleanMeClear = 61,
        EolTamperClear = 62,
        InternalLowBatteryClear = 63,
        PrimaryBatteryMissingClear = 64,
        PrimaryLowBatteryClear = 65,
        TamperClear = 66,
        LowSignalStrengthClear = 67,
        FirstVirtualActivation = 68,
        FirstVirtualActivationClear = 69,
        SecondVirtualActivation = 70,
        SecondVirtualActivationClear = 71,
        ThirdVirtualActivation = 72,
        ThirdVirtualActivationClear = 73,
        FourthVirtualActivation = 74,
        FourthVirtualActivationClear = 75,
        InfoOnly = 76,
        ClearByMagnet = 77,
        ClearByMagnetCleared = 78
    }
}
